### ISSUE TITLE
redefinition of typedef p_sdb_error_list

### ISSUE THREAD

**Issue by jeffdaily** [RonnySoak/libsdb#2]
gcc -Wall -O3 -std=c99 -march=native  -c -o src/libsdb.o src/libsdb.c
In file included from src/libsdb.c:11:
src/libsdb.h:23: error: redefinition of typedef ‘p_sdb_error_list’
src/sdb_error.h:29: note: previous declaration of ‘p_sdb_error_list’ was here

Looks like you create the same typedef in sdb_error.h:29 and then again (after including sdb_error.h) in libsdb.h:23.  I commented out the second definition and it worked for me.

**Comment by RonnySoak** [comment]
It's strange, somehow my compiler (gcc 4.8.4) did not report any redefinition ... nevertheless I removed it
