### ISSUE TITLE
where is the file "check.h" ?

### ISSUE THREAD

**Issue by jeffdaily** [RonnySoak/libsdb#3]
gcc -Wall -O3 -std=c99 -march=native  -c -o tests/test_database.o tests/test_database.c
In file included from tests/test_database.c:8:
tests/tests.h:11:19: error: check.h: No such file or directory

**Comment by RonnySoak** [comment]
The file check.h is part of the check unit testing library: http://check.sourceforge.net/

At the web page you can find installation instructions for most OS.
